<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SneakFit.ApiIntegration\SneakFit.ApiIntegration.csproj" />
    <ProjectReference Include="..\SneakFit.ViewModels\SneakFit.ViewModels.csproj" />
  </ItemGroup>

</Project>
